### ISSUE TITLE
release 0.5.5 available on search.maven.org but not tagged in git

### ISSUE THREAD

**Issue by jm-g** [lihaoyi/PPrint#32]
It is good practice to tag published releases in the source repository. To make it possible for users to find out which source corresponds to which release.

**Comment by jilen** [comment]
There are no `2.11` release of 0.5.5.

**Comment by jm-g** [comment]
Ok, then where is the source for the 2.12 and 2.13 releases. I am just wondering.

**Comment by lihaoyi** [comment]
I just found the tag in my local checkout and pushed it to github
