### ISSUE TITLE
calling pprintln from a generic function

### ISSUE THREAD

**Issue by dportabella** [lihaoyi/PPrint#7]
I used the following function with pprint 0.4.3:
```
  def myLogFunction[T](o: T)(implicit pp: pprint.PPrint[T]): T = {
    pprint.pprintln(o, width = 200)(pp)
    o
  }
```
The implicit PPrint was used by pprintln (`upickle-pprint/pprint/shared/src/main/scala/pprint/package.scala`)
```
  def pprintln[T: PPrint](t: T,
                          width: Integer = null,
                          height: Integer = null,
                          indent: Integer = null,
                          colors: Colors = null)
                         (implicit cfg: Config = Config.Defaults.PPrintConfig) = {


    tokenize(t, width, height, indent, colors)(implicitly[PPrint[T]], cfg).foreach(print)
    println()
  }
```

However, the last version of pprint, 0.5.2, does not use this implicit PPrint.
```
  def pprintln(x: Any,
              width: Int = defaultWidth,
              height: Int = defaultHeight,
              indent: Int = defaultIndent,
              initialOffset: Int = 0): Unit = {
    tokenize(x, width, height, indent, initialOffset).foreach(print)
    println()
  }
```

I can remove the implicit `PPrint` from my function, and it compiles, but `pprintln` uses the `T.toString` instead of pprint.
```
  def myLogFunction[T](o: T): T = {
    pprint.pprintln(o, width = 200)
    o
  }
```

How do I need to adapt `myLogFunction` to the last pprint version?
And how does `pprint` work without the previous implicit `PPrint`?

I tried revising the git history, but it seems that the git [upickle-pprint](https://github.com/lihaoyi/upickle-pprint) ends at 0.4.4, and the first version  of [PPrint](https://github.com/lihaoyi/PPrint) starts at 0.4.6, and it seems that it is between these two versions that the implicit PPrint has been removed.

**Comment by lihaoyi** [comment]
pprint no longer uses implicits, and just switches on a hard-coded list of classes. If you want to register your own classes for handling, you can do it via https://github.com/lihaoyi/PPrint/blob/master/pprint/shared/src/test/scala/test/pprint/AdvancedTests.scala#L98-L102

**Comment by dportabella** [comment]
so, i cannot write a generic `myLogFunction[T](o: T)` without knowing all the classes in advance?
