### ISSUE TITLE
how to customise the way string literals are printed?

### ISSUE THREAD

**Issue by dportabella** [lihaoyi/PPrint#8]
I'd like to use `org.apache.commons.lang.StringEscapeUtils.escapeJava` to print string literals.
How can I  customise `pprint` for doing so?

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/PPrint/blob/master/pprint/shared/src/test/scala/test/pprint/AdvancedTests.scala#L98-L102

http://www.lihaoyi.com/PPrint/#Customization

**Comment by dportabella** [comment]
It works, thanks.

```
import org.apache.commons.lang.StringEscapeUtils.escapeJava

object Test extends App {
  val additionalHandlers: PartialFunction[scala.Any, pprint.Tree] = {
    case x: String => pprint.Tree.Literal("\"" + escapeJava(x) + "\"")
  }
  val printer = pprint.copy(additionalHandlers = additionalHandlers)

  case class Person(name: String, age: Int, note: String)
  val p = Person(name = "John \"The First\"", age = 33, note = "first line\nsecond line")

  printer.pprintln(p)  // Person("John \"The First\"", 33, "first line\nsecond line")
}
```
Should I add this example to http://www.lihaoyi.com/PPrint/#Customization and make a pull request?
