### ISSUE TITLE
possibility to print an object all in one line (but still valid Scala code)

### ISSUE THREAD

**Issue by dportabella** [lihaoyi/PPrint#9]
It would be useful to have the possibility to print the object all in one line (but still valid Scala code).
Something like:
```
pprint.pprintln(p, width = None) //or
pprint.pprintln(p, width = 0))
```

**Comment by lihaoyi** [comment]
`pprint.pprintln(0, width = 99999999)`

**Comment by dportabella** [comment]
i think it's a bit ugly.  if not None, at least 0 or -1.
